version: '3.8'

services:
  frontend:
    image: your-registry/ipv6-frontend:latest
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://your-domain:3000/api
    restart: unless-stopped
    networks:
      - ipv6-network

  backend:
    image: your-registry/ipv6-backend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=ipv6_project
      - DB_USER=ipv6_user
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - xmap_results:/app/xmap_result
      - xmap_logs:/app/xmap_log
    networks:
      - ipv6-network

  xmap:
    image: teamzmap/xmap:latest
    container_name: ipv6-xmap
    volumes:
      - xmap_results:/data/results
      - xmap_logs:/data/logs
    restart: unless-stopped
    networks:
      - ipv6-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=ipv6_project
      - MYSQL_USER=ipv6_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - ipv6-network

volumes:
  mysql_data:
  xmap_results:
  xmap_logs:

networks:
  ipv6-network:
    driver: bridge
